UPDATE product_inv SET prod_color = 'Blue' WHERE prod_name = 'Blue Accent Chair';
UPDATE product_inv SET prod_color = 'Gray' WHERE prod_name = 'Industrial Gray Sectional Sofa';
UPDATE product_inv SET prod_color = 'Beige' WHERE prod_name = 'Beige Upholstered Dining Chairs';
UPDATE product_inv SET prod_color = 'Cream' WHERE prod_name = 'Curved Cream Dining Chairs';
UPDATE product_inv SET prod_color = 'Taupe' WHERE prod_name = 'Classic Tufted Sofa';
UPDATE product_inv SET prod_color = 'Taupe' WHERE prod_name = 'Taupe Dining Chairs';
UPDATE product_inv SET prod_color = 'White' WHERE prod_name = 'Modern White Armchair';
UPDATE product_inv SET prod_color = 'Light Gray' WHERE prod_name = 'Light Gray Sectional Sofa';
UPDATE product_inv SET prod_color = 'Beige' WHERE prod_name = 'Classic Dining Chair Set';
UPDATE product_inv SET prod_color = 'Gray' WHERE prod_name = 'Gray Metal Frame Sofa Set';