<?php
// ── Allowed locations ──────────────────────────────────────────
$provinces = [
  'Metro Manila','Cavite','Laguna','Batangas','Bulacan','Pampanga','Rizal',
  'Quezon','Nueva Ecija','Cebu','Davao del Sur','Iloilo','Bohol','Pangasinan',
  'Bicol Region','Negros Occidental','Negros Oriental','Leyte','Samar','Zamboanga del Sur',
  'Misamis Oriental','Bukidnon','Cagayan','Isabela','Benguet','Mountain Province',
  'Tarlac','Zambales','Bataan','Aurora','Quezon City (Standalone)'
];

$provinceCities = [
  'Metro Manila' => ['Manila','Quezon City','Makati','Pasig','Taguig','Parañaque','Caloocan','Las Piñas','Mandaluyong','Marikina','Muntinlupa','Navotas','Pasay','Pateros','San Juan','Valenzuela'],
  'Cavite'      => ['Cavite City','Bacoor','Imus','Dasmariñas','General Trias','Tagaytay','Trece Martires','Silang'],
  'Laguna'      => ['Calamba','Biñan','San Pedro','Santa Rosa','Cabuyao','Bay','Los Baños','Pagsanjan'],
  'Batangas'    => ['Batangas City','Lipa','Tanauan','Nasugbu','Rosario'],
  'Bulacan'     => ['Malolos','Meycauayan','San Jose del Monte','Marilao','Bocaue'],
  'Pampanga'    => ['San Fernando','Angeles','Mabalacat','Guagua'],
  'Rizal'       => ['Antipolo','Cainta','Taytay','Binangonan','Angono'],
  'Quezon'      => ['Lucena','Tayabas','Candelaria','Sariaya'],
  'Nueva Ecija' => ['Cabanatuan','San Jose','Gapan','Muñoz','Palayan'],
  'Cebu'        => ['Cebu City','Mandaue','Lapu-Lapu','Talisay','Danao','Carcar'],
  'Davao del Sur'=> ['Davao City','Digos'],
  'Iloilo'      => ['Iloilo City','Passi','Pototan'],
  'Bohol'       => ['Tagbilaran'],
  'Pangasinan'  => ['Dagupan','Urdaneta','San Carlos','Lingayen','Alaminos'],
  'Bicol Region' => ['Daet','Vinzons','Labo','Jose Panganiban','Mercedes','Capalonga','Naga','Iriga','Libmanan','Pili','Goa','Sipocot','Legazpi','Ligao','Tabaco','Polangui','Daraga','Sorsogon City','Bulan','Irosin','Masbate City','Cataingan','Virac'],
  'Negros Occidental'=> ['Bacolod','Bago','Cadiz','La Carlota','Sagay','Sipalay','Talisay','Victorias'],
  'Negros Oriental' => ['Dumaguete','Bais','Canlaon','Guihulngan','Tanjay'],
  'Leyte'           => ['Tacloban','Ormoc','Baybay','Palo'],
  'Samar'           => ['Catbalogan','Calbayog'],
  'Zamboanga del Sur'=> ['Zamboanga City','Pagadian','Dipolog'],
  'Misamis Oriental'=> ['Cagayan de Oro','Gingoog','El Salvador'],
  'Bukidnon'        => ['Malaybalay','Valencia'],
  'Cagayan'         => ['Tuguegarao','Aparri','Cauayan'],
  'Isabela'         => ['Ilagan','Cauayan','Santiago'],
  'Benguet'         => ['Baguio','La Trinidad','Itogon'],
  'Mountain Province'=> ['Bontoc'],
  'Tarlac'          => ['Tarlac City','Capas','Paniqui'],
  'Zambales'        => ['Olongapo','Iba','San Antonio'],
  'Bataan'          => ['Balanga','Mariveles','Orani'],
  'Aurora'          => ['Baler'],
];

$cityZipCodes = [
  'Manila' => '1000', 'Quezon City' => '1100', 'Makati' => '1200', 'Pasig' => '1600',
  'Taguig' => '1630', 'Parañaque' => '1700', 'Caloocan' => '1400', 'Las Piñas' => '1740',
  'Mandaluyong' => '1550', 'Marikina' => '1800', 'Muntinlupa' => '1770', 'Navotas' => '1485',
  'Pasay' => '1300', 'Pateros' => '1620', 'San Juan' => '1500', 'Valenzuela' => '1440',
  'Cavite City' => '4100', 'Bacoor' => '4102', 'Imus' => '4103',
  'Dasmariñas' => '4114', 'General Trias' => '4107', 'Tagaytay' => '4120', 'Trece Martires' => '4109', 'Silang' => '4118',
  'Santa Rosa' => '4026', 'San Pedro' => '4023', 'Biñan' => '4024', 'Calamba' => '4027',
  'Cabuyao' => '4025', 'Bay' => '4033', 'Los Baños' => '4030', 'Pagsanjan' => '4008',
  'Batangas City' => '4200', 'Lipa' => '4217', 'Tanauan' => '4232', 'Nasugbu' => '4211', 'Rosario' => '4225',
  'Malolos' => '3000', 'Meycauayan' => '3020', 'San Jose del Monte' => '3023', 'Marilao' => '3019', 'Bocaue' => '3018',
  'San Fernando' => '2000', 'Angeles' => '2009', 'Mabalacat' => '2010', 'Guagua' => '2003',
  'Antipolo' => '1870', 'Cainta' => '1900', 'Taytay' => '1920', 'Binangonan' => '1940', 'Angono' => '1930',
  'Lucena' => '4301', 'Tayabas' => '4327', 'Candelaria' => '4323', 'Sariaya' => '4322',
  'Cabanatuan' => '3100', 'San Jose' => '3121', 'Gapan' => '3105', 'Muñoz' => '3119', 'Palayan' => '3132',
  'Tuguegarao' => '3500', 'Aparri' => '3515', 'Cauayan' => '3305',
  'Cebu City' => '6000', 'Mandaue' => '6014', 'Lapu-Lapu' => '6015', 'Talisay' => '6045', 'Danao' => '6004', 'Carcar' => '6019',
  'Davao City' => '8000', 'Digos' => '8002',
  'Iloilo City' => '5000', 'Passi' => '5037', 'Pototan' => '5012',
  'Bacolod' => '6100', 'Bago' => '6101', 'Cadiz' => '6121', 'La Carlota' => '6130', 'Sagay' => '6122', 'Sipalay' => '6113',
  'Tagbilaran' => '6300',
  'Dagupan' => '2400', 'Urdaneta' => '2428', 'San Carlos' => '2420', 'Lingayen' => '2401', 'Alaminos' => '2404',
  'Daet' => '4600', 'Vinzons' => '4601', 'Labo' => '4603',
  'Jose Panganiban' => '4606', 'Mercedes' => '4604', 'Capalonga' => '4607',
  'Naga' => '4400', 'Iriga' => '4431', 'Libmanan' => '4407', 'Pili' => '4418', 'Goa' => '4422', 'Sipocot' => '4408',
  'Legazpi' => '4500', 'Ligao' => '4504', 'Tabaco' => '4511', 'Polangui' => '4506', 'Daraga' => '4501',
  'Sorsogon City' => '4700', 'Bulan' => '4706', 'Irosin' => '4707',
  'Masbate City' => '5400', 'Cataingan' => '5405',
  'Virac' => '4800',
  'Tacloban' => '6500', 'Ormoc' => '6541', 'Baybay' => '6521', 'Palo' => '6501',
  'Catbalogan' => '6700', 'Calbayog' => '6710',
  'Zamboanga City' => '7000', 'Pagadian' => '7016', 'Dipolog' => '7100',
  'Cagayan de Oro' => '9000', 'Gingoog' => '9014', 'El Salvador' => '9017',
  'Malaybalay' => '8700', 'Valencia' => '8709',
  'Ilagan' => '3300', 'Santiago' => '3311',
  'Baguio' => '2600', 'La Trinidad' => '2601', 'Itogon' => '2604',
  'Bontoc' => '2616',
  'Tarlac City' => '2300', 'Capas' => '2315', 'Paniqui' => '2307',
  'Olongapo' => '2200', 'Iba' => '2201', 'San Antonio' => '2212',
  'Balanga' => '2100', 'Mariveles' => '2105', 'Orani' => '2112',
  'Baler' => '3200',
  'Dumaguete' => '6200', 'Bais' => '6206', 'Canlaon' => '6208', 'Guihulngan' => '6214', 'Tanjay' => '6204',
];

$cities = array_values(array_unique(array_merge(...array_values($provinceCities))));

$cityBarangays = [
  'Manila'       => ['Binondo','Ermita','Intramuros','Malate','Paco','Pandacan','Port Area','Quiapo','Sampaloc','San Andres','San Miguel','San Nicolas','Santa Ana','Santa Cruz','Santa Mesa','Tondo'],
  'Quezon City'  => ['Bagong Pag-asa','Bagumbayan','Batasan Hills','Commonwealth','Cubao','Diliman','Fairview','Holy Spirit','Kamuning','Katipunan','Loyola Heights','Malaya','Novaliches','Project 4','Project 6','Project 7','Quirino 3-A','San Bartolome','Tandang Sora','UP Campus','White Plains'],
  'Makati'       => ['Bel-Air','Forbes Park','Guadalupe Nuevo','Guadalupe Viejo','Kasilawan','La Paz','Magallanes','Olympia','Palanan','Pembo','Pinagkaisahan','Pio del Pilar','Poblacion','Rembo','San Antonio','San Isidro','San Lorenzo','Santa Cruz','Singkamas','Tejeros','Urdaneta','Valenzuela'],
  'Pasig'        => ['Bagong Ilog','Bagong Katipunan','Bambang','Buting','Caniogan','Dela Paz','Kalawaan','Kapasigan','Kapitolyo','Malinao','Manggahan','Maybunga','Oranbo','Palatiw','Pinagbuhatan','Pineda','Rosario','Sagad','San Antonio','San Joaquin','San Jose','San Nicolas','Santa Lucia','Santa Rosa','Santo Tomas','Santolan','Sumilang','Ugong'],
  'Taguig'       => ['Bagumbayan','Bambang','Calzada','Cembo','Central','Comembo','East Rembo','Fort Bonifacio','Katuparan','Ligid-Tipas','Lower Bicutan','Maharlika Village','New Lower Bicutan','North Daang Hari','North Signal Village','Palingon','Pinagsama','San Miguel','Santa Ana','South Cembo','South Daang Hari','South Signal Village','Tanyag','Tuktukan','Upper Bicutan','Ususan','Wawa','West Rembo'],
  'Parañaque'    => ['Baclaran','BF Homes','Don Bosco','Don Galo','La Huerta','Marcelo Green','Merville','Moonwalk','San Antonio','San Dionisio','San Isidro','San Martin de Porres','Santo Niño','Sun Valley','Tambo','Vitalez'],
  'Caloocan'     => ['Bagong Barrio','Bagong Silang','Baesa','Camarin','Concepcion','Deparo','Grace Park','Llano','Maypajo','Monumento','Pag-asa','Pangarap','Pullman','San Jose','San Roque','Sangandaan','Tala','Tibag','University Hills','Wakas'],
  'Las Piñas'    => ['Almanza Dos','Almanza Uno','BF International','Daniel Fajardo','Elias Aldana','Ilaya','Manuyo Dos','Manuyo Uno','Pamplona Dos','Pamplona Tres','Pamplona Uno','Pilar','Pulang Lupa Dos','Pulang Lupa Uno','Talon Dos','Talon Kuatro','Talon Otso','Talon Tres','Talon Uno','Zapote'],
  'Mandaluyong'  => ['Addition Hills','Bagong Silang','Barangka Drive','Barangka Ilaya','Barangka Itaas','Barangka Ibaba','Buayang Bato','Burol','Daang Bakal','Hagdan Bato Itaas','Hagdan Bato Libis','Harapin Ang Bukas','Highway Hills','Hulo','Mabini-J. Rizal','Malamig','Mandaluyong','Mauway','Namayan','New Zañiga','Old Zañiga','Pag-asa','Plainview','Pleasant Hills','Poblacion','San Andres','San Joaquin','Vergara','Wack-Wack Greenhills'],
  'Marikina'     => ['Barangka','Calumpang','Concepcion Dos','Concepcion Uno','Fortune','Industrial Valley','Jesus dela Peña','Kalumpang','Malanday','Marikina Heights','Nangka','Parang','San Roque','Santa Elena','Santo Niño','Tañong','Tumana'],
  'Muntinlupa'   => ['Alabang','Ayala Alabang','Bayanan','Buli','Cupang','Poblacion','Putatan','Sucat','Tunasan'],
  'Pasay'        => ['Baclaran','Bangkal','Libertad','Malibay','Maricaban','Palanyag','San Isidro','Santa Clara','Villamor'],
  'San Juan'     => ['Addition Hills','Batis','Corazon de Jesus','Ermitaño','Greenhills','Isabelita','Kabayanan','Little Baguio','Maytunas','Onse','Pasadena','Pedro Cruz','Salapan','San Perfecto','St. Joseph','Tibagan','West Crame'],
  'Valenzuela'   => ['Arkong Bato','Bagbaguin','Balangkas','Bignay','Bisig','Canumay East','Canumay West','Coloong','Dalandanan','Gen. T. de Leon','Isla','Karuhatan','Lawang Bato','Lingunan','Mabolo','Malanday','Malinta','Mapulang Lupa','Marulas','Maysan','Palasan','Parada','Paso de Blas','Pasolo','Poblacion','Pulo','Punturin','Rincon','Tagalag','Ugong','Viente Reales','Wawang Pulo'],
  'Bacoor'       => ['Alima','Aniban I','Aniban II','Aniban III','Aniban IV','Aniban V','Banalo','Bayanan','Campo Santo','Daang Bukid','Digman','Dulong Bayan','Habay I','Habay II','Kaingin','Ligas I','Ligas II','Ligas III','Mabolo I','Mabolo II','Mabolo III','Maliksi I','Maliksi II','Maliksi III','Mambog I','Mambog II','Mambog III','Mambog IV','Mambog V','Molino I','Molino II','Molino III','Molino IV','Molino V','Molino VI','Niog I','Niog II','Niog III','Panapaan I','Panapaan II','Panapaan III','Panapaan IV','Panapaan V','Panapaan VI','Panapaan VII','Panapaan VIII','Queens Row Central','Queens Row East','Queens Row West','Real I','Real II','Salinas I','Salinas II','Salinas III','Salinas IV','San Nicolas I','San Nicolas II','San Nicolas III','Sineguelasan','Tabing Dagat','Talaba I','Talaba II','Talaba III','Talaba IV','Talaba V','Talaba VI','Talaba VII','Zapote I','Zapote II','Zapote III','Zapote IV','Zapote V'],
  'Imus'         => ['Alapan I-A','Alapan I-B','Alapan I-C','Alapan II-A','Alapan II-B','Anabu I-A','Anabu I-B','Anabu I-C','Anabu I-D','Anabu I-E','Anabu I-F','Anabu I-G','Anabu II-A','Anabu II-B','Anabu II-C','Anabu II-D','Anabu II-E','Buhay na Tubig','Carsadang Bago I','Carsadang Bago II','Magdalo','Malagasang I-A','Malagasang I-B','Malagasang I-C','Malagasang I-D','Malagasang I-E','Malagasang I-F','Malagasang I-G','Malagasang II-A','Malagasang II-B','Malagasang II-C','Malagasang II-D','Malagasang II-E','Malagasang II-F','Malagasang II-G','Mariano Espeleta I','Mariano Espeleta II','Mariano Espeleta III','Palico I','Palico II','Palico III','Palico IV','Pasong Buaya I','Pasong Buaya II','Poblacion I-A','Poblacion I-B','Poblacion II-A','Poblacion II-B','Poblacion III-A','Poblacion III-B','Tanzang Luma I','Tanzang Luma II','Tanzang Luma III','Tanzang Luma IV','Tanzang Luma V','Tanzang Luma VI','Tinabunan','Toclong I-A','Toclong I-B','Toclong I-C','Toclong II-A','Toclong II-B'],
  'Dasmariñas'   => ['Burol I','Burol II','Burol III','Burol Main','Datu Esmael','Emmanuel Bergado I','Emmanuel Bergado II','Fatima I','Fatima II','Fatima III','Habay','Langkaan I','Langkaan II','Luzviminda I','Luzviminda II','Maguay','Maliksi I','Maliksi II','Maliksi III','Paliparan I','Paliparan II','Paliparan III','Sabang','Salawag','Salitran I','Salitran II','Salitran III','Salitran IV','Sampaloc I','Sampaloc II','Sampaloc III','Sampaloc IV','Sampaloc V','San Agustin I','San Agustin II','San Agustin III','San Jose','San Lorenzo Ruiz I','San Lorenzo Ruiz II','San Miguel','San Simon','Santissimo Rosario','Santo Cristo I','Santo Cristo II','Zone I Poblacion','Zone II Poblacion','Zone III Poblacion'],
  'General Trias'=> ['Alingaro','Arnaldo','Bacao I','Bacao II','Bagumbayan','Biclatan','Buenavista I','Buenavista II','Buenavista III','Corregidor','Dulong Bayan','Gov. Ferrer','Javalera','Manggahan','Navarro','Ninety Ninth','Panungyanan','Pasong Camachile I','Pasong Camachile II','Pasong Kawayan I','Pasong Kawayan II','Pinagtipunan','Poblacion I','Poblacion II','Poblacion III','Prinza','Sab-a Basin','San Francisco','San Gabriel','San Juan I','San Juan II','Santiago','Tapia','Tejero','Vibora'],
  'Tagaytay'     => ['Asisan','Bagong Tubig','Calabuso','Diokno','Francisco','Guinhawa North','Guinhawa South','Iruhin Central','Iruhin East','Iruhin West','Kaybagal Central','Kaybagal East','Kaybagal North','Kaybagal South','Mag-asawang Ilat','Maharlika East','Maharlika West','Mendez Crossing East','Mendez Crossing West','Mitayin','Neogan','Patutong Malaki North','Patutong Malaki South','Sambong','San Jose','Silang Junction North','Silang Junction South','Sungay East','Sungay West','Tolentino East','Tolentino West','Zambal'],
  'Calamba'      => ['Bagong Kalsada','Banadero','Banlic','Barandal','Batino','Bubuyan','Bucal','Bunggo','Burol','Camaligan','Canlubang','Kay-anlog','La Mesa','Laguerta','Lawa','Lecheria','Lingga','Looc','Mabato','Makiling','Majada Out','Majada Labas','Minola','Paciano Rizal','Palingon','Palo-Alto','Pansol','Parian','Prinza','Punta','Puting Lupa','Real','Saimsim','Sampiruhan','San Cristobal','San Jose','San Juan','Sirang Lupa','Sucol','Tulo','Turbina','Ulango','Uwisan'],
  'Biñan'        => ['Biñan','Canlalay','Casile','De La Paz','Ganado','Loma','Luis Luz','Malaban','Malamig','Mamplasan','Platero','Poblacion','San Antonio','San Francisco','San Jose','San Vicente','Santo Domingo','Santo Niño','Santo Tomas','Soro-soro','Timbao','Tubigan','Zapote'],
  'San Pedro'    => ['Bagong Silang','Calendola','Chrysanthemum','Cuyab','Estrella','Fatima','G.S.I.S.','Landayan','Langgam','Laram','Magsaysay','Maharlika','Narra','Nueva','Pacita 1','Pacita 2','Poblacion','Riverside','Sampaguita','San Antonio','United Bayanihan','United Better Living'],
  'Santa Rosa'   => ['Aplaya','Balibago','Caingin','Dila','Dita','Don Jose','Ibaba','Kanluran','Labas','Macabling','Malitlit','Malusak','Market Area','Pooc','Pulong Santa Cruz','Sinalhan','Tagapo'],
  'Cabuyao'      => ['Baclaran','Banay-Banay','Banlic','Bigaa','Butong','Casile','Diezmo','Gulod','Mamatid','Marinig','Niugan','Pittland','Pulo','San Isidro','Sala'],
  'Batangas City'=> ['Alangilan','Arce','Balagtas','Balete','Banaba Center','Bilogo','Bolbok','Bukal','Calicanto','Cuta','Dalig','Dela Paz','Dela Paz Proper','Domoclay','Dumuclay','Gulod Itaas','Gulod Labas','Ilihan','Kumintang Ibaba','Kumintang Ilaya','Libjo','Maapaz','Mahabang Parang','Malamig','Marunos','Mataas na Lupa','Matamis','Matlang','Pag-asa','Paharang Kanluran','Paharang Silangan','Palahanan I','Palahanan II','Pamilhan','Puting Bato East','Puting Bato West','Sambat','San Isidro','San Jose Sico','San Pedro','Simlong','Sirang Lupa','Tulo','Wawa'],
  'Lipa'         => ['Adya','Anilao','Anilao-Labac','Antipolo Del Norte','Antipolo Del Sur','Bagong Pook','Balintawak','Banaybanay','Bolbok','Bulacan','Bungahan','Calamias','Cumba','Dagatan','Duhatan','Halang','Inosluban','Kayumanggi','Latag','Lodlod','Lumbang','Mabini','Malagonlong','Malitlit','Marawoy','Mataas Na Lupa','Morado','Pinagkawitan','Pinagtongulan','Plaridel','Quezon','Rizal','Sabang','Sampaguita','San Benito','San Carlos','San Celestino','San Francisco','San Guillermo','San Isidro','San Jose','San Lucas','San Salvador','San Sebastian','Santo Niño','Sapac','Sico','Talisay','Tambo','Tangob','Tanguay','Tibig','Tinatagan','Tuy','Wawa'],
  'Antipolo'     => ['Bagong Nayon','Beverly Hills','Calawis','Cupang','Dalig','Dela Paz','Inarawan','Mambugan','Mayamot','Muyong','San Isidro','San Jose','San Juan','San Luis','San Roque','Santa Cruz','Santo Niño','Sinag','Tartaria'],
  'Cainta'       => ['Banting','Dayap','Karangalan Village','Niño Jesus','Parang','Poblacion','San Andres','San Juan','Santo Domingo','Santo Niño'],
  'Taytay'       => ['Dolores','Muzon','Poblacion','San Isidro','San Juan','Santa Ana'],
  'Cebu City'    => ['Adlaon','Agsungot','Apas','Babag','Bacayan','Banilad','Basak Pardo','Basak San Nicolas','Binaliw','Bonbon','Budlaan','Busay','Calamba','Cambinocot','Capitol Site','Carreta','Central','Cogon Pardo','Cogon Ramos','Day-as','Duljo','Ermita','Guadalupe','Guba','Hippodromo','Inayawan','Kalubihan','Kalunasan','Kamagayan','Kasambagan','Kinasang-an','Labangon','Lahug','Lorega','Lusaran','Luz','Mabini','Mabolo','Malubog','Mambaling','Mohon','Pardo','Pari-an','Paril','Pasil','Pit-os','Pulangbato','Punta Princesa','Quiot Pardo','Sambag I','Sambag II','San Antonio','San Jose','San Nicolas Central','San Nicolas Proper','San Roque','Santa Cruz','Santo Niño','Sapangdaku','Sawang Calero','Sinsin','Sompotan','T. Padilla','Tabunan','Tagba-o','Taptap','Tejero','Tinago','Tisa','To-ong Pardo','Tuburan','Tungkop'],
  'Mandaue'      => ['Alang-alang','Bakilid','Banilad','Basak','Cambaro','Canduman','Casili','Casuntingan','Centro','Cubacub','Guizo','Ibabao-Estancia','Jagobiao','Labogon','Looc','Maguikay','Mahiga','Mantuyong','Opao','Pakna-an','Paknaan','Subangdaku','Tabok','Tawason','Tingub','Tipolo','Umapad'],
  'Davao City'   => ['Agdao','Bago Aplaya','Bago Gallera','Bago Oshiro','Baliok','Bangkas Heights','Bantol','Baracatan','Biao Escuela','Biao Guianga','Biao Joaquin','Binugao','Bucana','Buda','Buhangin','Bunawan','Cabantian','Cadalian','Calinan','Callawa','Camansi','Carmen','Catalunan Grande','Catalunan Pequeño','Catigan','Cawayan','Centro','Communal','Crossing Bayabas','Dacudao','Dalag','Dalagdag','Daliao','Datu Salumay','Dumoy','Eden','Fatima','Gatungan','Gov. Paciano Bangoy','Gov. Vicente Duterte','Gumalang','Ilang','Indangan','Lacson','Lamanan','Lampianao','Langub','Lapu-lapu','Las Palmas','Lasang','Leon Garcia Sr.','Lizada','Los Amigos','Lubogan','Lumiad','Ma-a','Mabuhay','Magsaysay','Magtuod','Mahayag','Malabog','Malagos','Malalag','Manambulan','Mandug','Manuel Guianga','Mapula','Marapangi','Matina Aplaya','Matina Biao','Matina Crossing','Matina Pangi','Megkawayan','Mintal','Mudiang','Mulig','New Carmen','New Valencia','Panacan','Paradise Embak','Paquibato','Piapi','Poblacion','Puan','Puting Bato','Riverside','Salapawan','Salaysay','Saloy','San Antonio','San Isidro','Santos','Sasa','Sirib','Suawan','Subasta','Tacunan','Tagakpan','Tagluno','Tagurano','Talandang','Talomo','Talomo River','Tamayong','Tambobong','Tamugan','Tapak','Tawan-Tawan','Tibuloy','Tibungco','Tidman','Tigatto','Toril','Tugbok','Tungkalan','Ubalde','Ula','Unidos','Wangan','Wilfredo Aquino','Wines'],
  'Iloilo City'  => ['Aguinaldo','Airport','Alday','Arevalo','Balabago','Balantang','Bakhaw','Benedicto','Bo. Obrero','Bolilao','Boulevard','Bonifacio','Buenavista','Buntatala','Burgos Poblacion','Calaparan','Calumpang','Compania','Cuartero','Danao','Del Lima','Demoledor','Desamparados','Divinagracia','Dungon A','Dungon B','Dungon C','East Timawa','Edganzon','El 98','Fajardo','Geronimo','Gloria','Gustilo','Hibao-an Norte','Hibao-an Sur','Hinactacan','Ingore','Jalandoni Estate','Jalandoni-Wilson','Javellana','Jereos','Kahirupan','Kauswagan','Laguda','Lapuz Norte','Lapuz Sur','Leganes','Libertad-Santa Isabel','Libertad','Lio-an','Loboc','Lopez Jaena Norte','Lopez Jaena Sur','Luna','M.V. Hechanova','Mabolo','Magsaysay','Mansaya-Lapuz','Montinola','Nabitasan','North Baluarte','North Fundidor','Oasis','Palapala','Pale Benedicto Rizal','Pelago','Pison-Labao','Poblacion Molo','Progreso','Punong','Quezon','Quintin Salas','Rizal Palapala I','Rizal Palapala II','Roxas Village','Sambag','Sampaguita','San Agustin','San Felix','San Isidro Norte','San Isidro Sur','San Jose','San Juan','Santa Cruz','Santo Niño Norte','Santo Niño Sur','Santo Rosario','Seminario','Simon Ledesma','Sooc','Taal','Tabucan','Tacas','Tagbac','Tanza-Baybay','Tap-oc','Timawa Tanza I','Timawa Tanza II','Ungka I','Ungka II','Veterans Village','Villa Anita','West Habog-habog','West Timawa','Yulo Drive','Yulo-Arroyo','Zulueta-Delgado'],
  'Tagbilaran'   => ['Bool','Booy','Cogon','Dampas','Dao','Manga','Mansasa','Poblacion I','Poblacion II','Poblacion III','San Isidro','Taloto','Tiptip','Ubujan'],
  'Dagupan'      => ['Bacayao Norte','Bacayao Sur','Barangay I (Poblacion)','Barangay II (Poblacion)','Barangay III (Poblacion)','Barangay IV (Poblacion)','Bonuan Binloc','Bonuan Boquig','Bonuan Gueset','Calmay','Carael','Caranglaan','Herrero','Lasip Chico','Lasip Grande','Lomboy','Lucao','Malued','Mamalingling','Mangin','Mayombo','Pantal','Pogo Chico','Pogo Grande','Pugaro Suit','Salapingao','Tambac','Tapuac','Tebeng'],
  'Naga'         => ['Abella','Bagumbayan Norte','Bagumbayan Sur','Balatas','Calauag','Cararayan','Carolina','Concepcion Grande','Concepcion Pequeño','Dayangdang','Del Rosario','Dinaga','Igualdad Interior','Lerma','Liboton','Mabolo','Pacol','Panicuason','Peñafrancia','Sabang','San Felipe','San Francisco','Santa Cruz','Tabuco','Tinago','Triangulo'],
];

